version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.5

executors:
  default:
    resource_class: small
    docker:
      - image: cimg/ruby:3.2.2-node
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"

jobs:
  build:
    executor: default
    resource_class: small
    steps:
      - checkout
      - run:
          name: Build static site
          command: make html
      - persist_to_workspace:
          root: build
          paths:
            - .

  deploy:
    executor: default
    parameters:
      environment:
        description: Deployment environment
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: build
      - aws-cli/install
      - run:
          name: Upload to S3
          command: |
            cd build/
            aws s3 sync . s3://trade-tariff-api-docs-<< parameters.environment >>

workflows:
  version: 2
  ci:
    jobs:
      - build:
          context: trade-tariff

      - deploy:
          name: deploy_development
          context: trade-tariff-bot-aws-development
          environment: development
          filters:
            branches:
              ignore: [main]
          requires: [build]

      - deploy:
          name: deploy_staging
          context: trade-tariff-bot-aws-staging
          environment: staging
          filters:
            branches:
              only: [main]
          requires: [build]

      - hold_deploy_production:
          type: approval
          requires: [deploy_staging]
          filters:
            branches:
              only: [main]

      - deploy:
          name: deploy_production
          context: trade-tariff-bot-aws-production
          environment: production
          filters:
            branches:
              only: [main]
          requires: [build]
