version: 2.1

filter-not-main: &filter-not-main
  filters:
    branches:
      ignore:
        - main
        - /^dependabot/(?!docker/).*/
        - /^hotfix\/.+/

filter-main: &filter-main
  filters:
    branches:
      only:
        - main
        - /^hotfix\/.+/

orbs:
  aws-cli: circleci/aws-cli@3.1.5

executors:
  default:
    resource_class: small
    docker:
      - image: cimg/ruby:3.2.2-node
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"

jobs:
  build:
    executor: default
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install graphviz
          command: sudo apt-get update && sudo apt-get install -yy graphviz
      - run:
          name: Build static site
          command: make html
      - persist_to_workspace:
          root: build
          paths:
            - .

  deploy:
    executor: default
    parameters:
      environment:
        description: Deployment environment
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: build
      - aws-cli/install
      - run:
          name: Upload to S3
          command: |
            cd build/
            aws s3 sync . s3://trade-tariff-api-docs-<< parameters.environment >>

workflows:
  version: 2

  deploy-to-development:
    jobs:
      - build:
          name: build-dev
          context: trade-tariff
          <<: *filter-not-main

      - deploy:
          name: deploy-dev
          context: trade-tariff-terraform-aws-development
          environment: "844815912454"
          <<: *filter-not-main
          requires:
            - build-dev

  deploy-to-staging:
    jobs:
      - build:
          name: build-staging
          context: trade-tariff
          <<: *filter-main

      - deploy:
          name: deploy-staging
          context: trade-tariff-terraform-aws-staging
          environment: "451934005581"
          <<: *filter-main
          requires:
            - build-staging

  deploy-to-production:
    jobs:
      - build:
          name: build-prod
          context: trade-tariff
          <<: *filter-main

      - deploy:
          name: deploy-prod
          context: trade-tariff-terraform-aws-production
          environment: "382373577178"
          <<: *filter-main
          requires:
            - build-prod
