# Host to use for canonical URL generation (without trailing slash)
host: https://api.trade-tariff.service.gov.uk

# Header-related options
show_govuk_logo: true
service_link: /
govuk_homepage_url: https://www.gov.uk

# Links to show on right-hand-side of header
header_links:
  About: /
  Developer portal: /developer-portal.html
  API Reference: /reference.html
  Trade Tariff API: /the-trade-tariff-api.html
  Categorisation API: /categorisation.html
  FPO API: /fpo.html
  MCP Server: /mcp.html

# Footer meta links
footer_links:
  Privacy policy: https://www.trade-tariff.service.gov.uk/privacy
  Cookies: https://www.trade-tariff.service.gov.uk/cookies
  Terms and conditions: https://www.trade-tariff.service.gov.uk/terms

# Google Analytics 4 via Google Tag Manager (same container as Developer Portal)
ga4_gtm_tracking_id: GTM-KPM7NRDG

# Table of contents depth – how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 6

# Prevent robots from indexing (e.g. whilst in development)
prevent_indexing: false
