name: Reusable Build

on:
  workflow_call:
    inputs:
      environment:
        description: "The name of the environment the build is for"
        required: true
        type: string

    outputs:
       artifact-name:
         description: "The name of the uploaded artifact"
         value: build-artifact

jobs:
  build:
    env:
      ENVIRONMENT: ${{ inputs.environment }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1

      - uses: ruby/setup-ruby@v1.321.0
        with:
          bundler-cache: true

      - name: Install graphviz
        run: sudo apt-get update && sudo apt-get install -yy graphviz

      - name: Build static site
        run: make html

      - name: Run layout and content tests
        run: make test

      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v7
        with:
          name: build-artifact
          path: build/
