name: Deploy to staging

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - hotfix/*

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: eu-west-2
  ENVIRONMENT: "451934005581"
  IAM_ROLE_ARN: arn:aws:iam::451934005581:role/GithubActions-API-Docs-Role

jobs:
  build-staging:
    uses: ./.github/workflows/build.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build-staging

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: build-artifact
        path: build/

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.IAM_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Upload to S3
      run: |
        cd build/
        aws s3 sync . s3://trade-tariff-api-docs-${{ env.ENVIRONMENT }} --delete
