name: Deploy to production

on:
  push:
    branches:
    - main
  # workflow_run:
  #   workflows:
  #     - 'Deploy to staging'
  #   types:
  #     - completed
  workflow_dispatch:
    inputs:
      ref:
        description: 'The git ref to deploy'
        required: true
        default: 'main'

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: eu-west-2
  ENVIRONMENT: "382373577178"
  IAM_ROLE_ARN: arn:aws:iam::382373577178:role/GithubActions-API-Docs-Role

jobs:
  build-prod:
    uses: ./.github/workflows/build.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build-prod

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: build-artifact
        path: build/

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.IAM_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Upload to S3
      run: |
        cd build/
        aws s3 sync . s3://trade-tariff-api-docs-${{ env.ENVIRONMENT }} --delete

    - name: Invalidate cache
      run: |
        DISTRIBUTION_ID=$(aws cloudfront list-distributions \
          --query "DistributionList.Items[*].{id:Id,origin:Origins.Items[0].Id}[?origin=='api'].id" \
          --output text)

        aws cloudfront create-invalidation \
          --distribution-id "${DISTRIBUTION_ID}" \
          --paths "/*"
